import { Product } from '../types/product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Signature Blend #1',
    slug: 'signature-blend-1',
    description: 'A rich and balanced coffee with notes of chocolate, caramel, and a hint of citrus. Perfect for your morning routine.',
    short_description: 'Rich and balanced with chocolate and caramel notes',
    price: 18.99,
    wholesale_price: 14.99,
    sku: 'SB001',
    category_id: '1',
    category_name: 'Coffee',
    weight_grams: 340,
    origin: 'Colombia',
    roast_level: 'Medium',
    flavor_notes: 'Chocolate, Caramel, Citrus',
    image_url: '/images/products/signature-blend-1.jpg',
    is_active: true,
    is_featured: true,
    inventory_quantity: 50,
    meta_title: 'Signature Blend #1 - Premium Coffee',
    meta_description: 'Rich and balanced coffee with chocolate and caramel notes',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '2',
    name: 'Signature Blend #2',
    slug: 'signature-blend-2',
    description: 'A bold and full-bodied coffee with deep earthy tones and a smooth finish. Ideal for coffee enthusiasts.',
    short_description: 'Bold and full-bodied with earthy tones',
    price: 19.99,
    wholesale_price: 15.99,
    sku: 'SB002',
    category_id: '1',
    category_name: 'Coffee',
    weight_grams: 340,
    origin: 'Ethiopia',
    roast_level: 'Dark',
    flavor_notes: 'Earthy, Smoky, Bold',
    image_url: '/images/products/signature-blend-2.jpg',
    is_active: true,
    is_featured: true,
    inventory_quantity: 30,
    meta_title: 'Signature Blend #2 - Bold Coffee',
    meta_description: 'Bold and full-bodied coffee with earthy tones',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '3',
    name: 'Signature Blend #3',
    slug: 'signature-blend-3',
    description: 'A light and bright coffee with floral notes and a clean finish. Perfect for afternoon enjoyment.',
    short_description: 'Light and bright with floral notes',
    price: 17.99,
    wholesale_price: 13.99,
    sku: 'SB003',
    category_id: '1',
    category_name: 'Coffee',
    weight_grams: 340,
    origin: 'Kenya',
    roast_level: 'Light',
    flavor_notes: 'Floral, Bright, Clean',
    image_url: '/images/products/signature-blend-3.jpg',
    is_active: true,
    is_featured: false,
    inventory_quantity: 25,
    meta_title: 'Signature Blend #3 - Light Coffee',
    meta_description: 'Light and bright coffee with floral notes',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '4',
    name: 'Espresso Roast',
    slug: 'espresso-roast',
    description: 'A dark and intense roast perfect for espresso drinks. Rich crema and bold flavor profile.',
    short_description: 'Dark and intense for espresso drinks',
    price: 21.99,
    wholesale_price: 17.99,
    sku: 'ER001',
    category_id: '1',
    category_name: 'Coffee',
    weight_grams: 340,
    origin: 'Brazil',
    roast_level: 'Dark',
    flavor_notes: 'Intense, Bitter, Rich',
    image_url: '/images/products/espresso-roast.jpg',
    is_active: true,
    is_featured: false,
    inventory_quantity: 40,
    meta_title: 'Espresso Roast - Dark Coffee',
    meta_description: 'Dark and intense roast perfect for espresso',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '5',
    name: 'Decaf Blend',
    slug: 'decaf-blend',
    description: 'A smooth and flavorful decaffeinated coffee that doesn\'t compromise on taste. Perfect for evening enjoyment.',
    short_description: 'Smooth decaf without compromising taste',
    price: 16.99,
    wholesale_price: 12.99,
    sku: 'DB001',
    category_id: '1',
    category_name: 'Coffee',
    weight_grams: 340,
    origin: 'Colombia',
    roast_level: 'Medium',
    flavor_notes: 'Smooth, Balanced, Decaf',
    image_url: '/images/products/decaf-blend.jpg',
    is_active: true,
    is_featured: false,
    inventory_quantity: 20,
    meta_title: 'Decaf Blend - Decaffeinated Coffee',
    meta_description: 'Smooth decaf coffee without compromising taste',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  },
  {
    id: '6',
    name: 'Coffee Mug',
    slug: 'coffee-mug',
    description: 'A premium ceramic mug perfect for enjoying your favorite coffee. Dishwasher safe and microwave friendly.',
    short_description: 'Premium ceramic mug for coffee lovers',
    price: 12.99,
    wholesale_price: 8.99,
    sku: 'CM001',
    category_id: '2',
    category_name: 'Equipment',
    weight_grams: 300,
    origin: 'USA',
    roast_level: 'N/A',
    flavor_notes: 'N/A',
    image_url: '/images/products/coffee-mug.jpg',
    is_active: true,
    is_featured: false,
    inventory_quantity: 100,
    meta_title: 'Coffee Mug - Premium Ceramic',
    meta_description: 'Premium ceramic mug for coffee lovers',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z'
  }
];

export const MOCK_CATEGORIES = [
  {
    id: '1',
    name: 'Coffee',
    slug: 'coffee',
    description: 'Premium roasted coffee beans',
    image_url: '/images/categories/coffee.jpg',
    is_active: true,
    sort_order: 1
  },
  {
    id: '2',
    name: 'Equipment',
    slug: 'equipment',
    description: 'Coffee brewing equipment and accessories',
    image_url: '/images/categories/equipment.jpg',
    is_active: true,
    sort_order: 2
  },
  {
    id: '3',
    name: 'Merchandise',
    slug: 'merchandise',
    description: 'Vendetta Roasting branded merchandise',
    image_url: '/images/categories/merchandise.jpg',
    is_active: true,
    sort_order: 3
  }
];
